---
- name: Adminstart
  become: true
  shell: /usr/local/sbin/adminstart-auto

- name: Install and configure AIDE
  become: true
  yum:
    name: aide
    state: latest

- name: Check SELinux
  become: false
  shell: /usr/sbin/getenforce
  register: selinux

- name: Set SELinux fact
  set_facts:
    has_selinux: yes
  when: 'selinux.stdout == "Enforcing" or selinux.stdout == "Permissive"'

- name: Set SELinux fact
  set_facts:
    has_selinux: no
  when: 
    - selinux.stdout != "Enforcing" 
    - selinux.stdout != "Permissive"

- name: Copy RHEL7 aide.conf
  become: true
  template:
    src: ../files/aide-rhel7.j2
    dest: /etc/aide.conf
    mode: 0600
    attributes: +i
  when: '"el7" in release.stdout'

- name: Copy RHEL8 aide.conf
  become: true
  template:
    src: ../files/aide-rhel8.j2
    dest: /etc/aide.conf
    mode: 0600
    attributes: +i
  when: '"el8" in release.stdout'

- name: Copy RHEL9 aide.conf
  become: true
  template:
    src: ../files/aide-rhel9.j2
    dest: /etc/aide.conf
    mode: 0600
    attributes: +i
  when: '"el9" in release.stdout'

- name: Copy Debian/Ubuntu aide.conf
  become: true
  copy:
    src: ../files/98_aide_scdrm
    dest: /etc/aide/aide.conf.d/98_aide_scdrm
    mode: 0644
    attributes: +i
  when: '"generic" in release.stdout or "amd64" in release.stdout'

- name: Copy aide-auto-check
  become: true
  template:
    src: ../files/aide-auto-check.j2
    dest: /usr/local/sbin/aide-auto-check
    mode: 0750
    attributes: +i
  when: aide_auto_check is defined

- name: AIDE init
  become: true
  shell: /usr/sbin/aide -i && mv /var/lib/aide/aide.db.new.gz /var/lib/aide/aide.db.gz

- name: Setup AIDE check RHEL7
  become: true
  copy:
    content: |
      [Unit]
      Description=AIDE check

      [Service]
      Type=simple
      ExecStart=/usr/sbin/aide -C > /var/log/aide/aide.log
      Restart=on-failure
      RestartSec=30m

      [Install]
      WantedBy=scdrm.service
    dest: /etc/systemd/system/aide-check.service
    mode: 0644
    owner: root
    group: root
    attributes: +i
  when: '"el7" in release.stdout'

- name: Setup AIDE check RHEL89
  become: true
  copy:
    content: |
      [Unit]
      Description=AIDE check

      [Service]
      Type=simple
      ExecStart=/usr/sbin/aide --check
      Restart=on-failure
      RestartSec=30m

      [Install]
      WantedBy=scdrm.service
    dest: /etc/systemd/system/aide-check.service
    mode: 0644
    owner: root
    group: root
    attributes: +i
  when: '"el7" not in release.stdout'

- name: Setup AIDE check timer
  become: true
  copy:
    content: |
      [Unit]
      Description=AIDE check timer

      [Timer]
      OnCalendar={{ aide_check }}
      RandomizedDelaySec=8h
      AccuracySec=1us
      Persistent=true

      [Install]
      WantedBy=timers.target
    dest: /etc/systemd/system/aide-check.timer
    mode: 0644
    owner: root
    group: root
    attributes: +i

- name: Setup AIDE auto-check
  become: true
  copy:
    content: |
      [Unit]
      Description=AIDE auto-check

      [Service]
      Type=simple
      ExecStart=/usr/local/sbin/aide-auto-check
      #Restart=on-failure

      [Install]
      WantedBy=scdrm.service
    dest: /etc/systemd/system/aide-auto-check.service
    mode: 0644
    owner: root
    group: root
    attributes: +i
  when:
    - aide_auto_check is defined

- name: Setup AIDE auto-check timer
  become: true
  copy:
    content: |
      [Unit]
      Description=AIDE auto-check timer

      [Timer]
      OnCalendar=*/2
      RandomizedDelaySec=1m
      AccuracySec=1us
      Persistent=true

      [Install]
      WantedBy=timers.target
    dest: /etc/systemd/system/aide-auto-check.timer
    mode: 0644
    owner: root
    group: root
    attributes: +i
  when: aide_auto_check is defined

- name: Commit AIDE install
  become: true
  shell: cd /etc && git add aide.conf logrotate.d/aide && git commit -a -m "Aide installed"

- name: Service start
  become: true
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: restarted
    daemon_reload: yes
  with_items:
    - aide-check.timer
    - aide-check.service

- name: Adminstop
  become: true
  shell: /usr/local/sbin/adminstop-auto
...
