---
- name: Adminstart
  become: true
  command: /usr/local/sbin/adminstart-auto
  changed_when: false

- name: Install and configure AIDE
  become: true
  package:
    name: aide
    state: present

- name: Create log dir if not present
  become: true
  file:
    path: /var/log/aide
    state: directory
    mode: 0750

- name: Check SELinux
  become: false
  command: /usr/sbin/getenforce
  changed_when: false
  register: selinux
  when: '"el" in release.stdout'

- name: Set SELinux fact
  set_fact:
    hasselinux: true
  when:
    - '"el" in release.stdout'
    - selinux.stdout == "Enforcing" or selinux.stdout == "Permissive"

- name: Set SELinux fact
  set_fact:
    hasselinux: false
  when:
    - '"el" in release.stdout'
    - selinux.stdout != "Enforcing"
    - selinux.stdout != "Permissive"

- name: Set SELinux fact
  set_fact:
    hasselinux: false
  when:
    - '"Debian" in distro.stdout or "Ubuntu" in distro.stdout'
    - selinux is not defined

- name: Copy RHEL7 aide.conf
  become: true
  template:
    src: ../files/aide-rhel7.j2
    dest: /etc/aide.conf
    mode: 0600
    attributes: +i
  when: '"el7" in release.stdout'

- name: Copy RHEL8 aide.conf
  become: true
  template:
    src: ../files/aide-rhel8.j2
    dest: /etc/aide.conf
    mode: 0600
    attributes: +i
  when: '"el8" in release.stdout'

- name: Copy RHEL9 aide.conf
  become: true
  template:
    src: ../files/aide-rhel9.j2
    dest: /etc/aide.conf
    mode: 0600
    owner: root
    attributes: +i
  when: '"el9" in release.stdout'

- name: Copy Debian/Ubuntu aide.conf
  become: true
  copy:
    src: ../files/98_aide_scdrm
    dest: /etc/aide/aide.conf.d/98_aide_scdrm
    mode: 0644
    owner: root
    attributes: +i
  when: '"Debian" in distro.stdout or "Ubuntu" in distro.stdout'

- name: Copy aide-auto-check
  become: true
  template:
    src: ../files/aide-auto-check.j2
    dest: /usr/local/sbin/aide-auto-check
    mode: 0750
    attributes: +i
  when: aide_auto_check is defined

- name: AIDE init EL
  become: true
  shell: /usr/sbin/aide -i && mv /var/lib/aide/aide.db.new.gz /var/lib/aide/aide.db.gz
  args:
    executable: /bin/bash
  when: '"el" in release.stdout'

- name: AIDE init Deb
  become: true
  shell: /usr/bin/aide -c /etc/aide/aide.conf -i && mv /var/lib/aide/aide.db.new /var/lib/aide/aide.db
  args:
    executable: /bin/bash
  when: '"el" not in release.stdout'

- name: Setup AIDE check RHEL7
  become: true
  copy:
    content: |
      [Unit]
      Description=AIDE check

      [Service]
      Type=simple
      ExecStart=/usr/sbin/aide -C > /var/log/aide/aide.log
      Restart=on-failure
      RestartSec=30m

      [Install]
      WantedBy=scdrm.service
    dest: /etc/systemd/system/aide-check.service
    mode: 0644
    owner: root
    group: root
    attributes: +i
  when: '"el7" in release.stdout'

- name: Setup AIDE check RHEL89
  become: true
  copy:
    content: |
      [Unit]
      Description=AIDE check

      [Service]
      Type=simple
      ExecStart=/usr/sbin/aide --check
      Restart=on-failure
      RestartSec=30m

      [Install]
      WantedBy=scdrm.service
    dest: /etc/systemd/system/aide-check.service
    mode: 0644
    owner: root
    group: root
    attributes: +i
  when: '"el8" in release.stdout or "el9" in release.stdout'

- name: Setup AIDE check Debian
  become: true
  copy:
    content: |
      [Unit]
      Description=AIDE check

      [Service]
      Type=simple
      ExecStart=/usr/bin/aide -c /etc/aide/aide.conf --check > /var/log/aide/aide.log
      Restart=on-failure
      RestartSec=30m

      [Install]
      WantedBy=scdrm.service
    dest: /etc/systemd/system/aide-check.service
    mode: 0644
    owner: root
    group: root
    attributes: +i
  when: '"el" not in release.stdout'

- name: Setup AIDE check timer
  become: true
  copy:
    content: |
      [Unit]
      Description=AIDE check timer

      [Timer]
      OnCalendar={{ aide_check }}
      RandomizedDelaySec=8h
      AccuracySec=1us
      Persistent=true

      [Install]
      WantedBy=timers.target
    dest: /etc/systemd/system/aide-check.timer
    mode: 0644
    owner: root
    group: root
    attributes: +i

- name: Setup AIDE auto-check
  become: true
  copy:
    content: |
      [Unit]
      Description=AIDE auto-check

      [Service]
      Type=simple
      ExecStart=/usr/local/sbin/aide-auto-check
      #Restart=on-failure

      [Install]
      WantedBy=scdrm.service
    dest: /etc/systemd/system/aide-auto-check.service
    mode: 0644
    owner: root
    group: root
    attributes: +i
  when:
    - aide_auto_check is defined

- name: Setup AIDE auto-check timer
  become: true
  copy:
    content: |
      [Unit]
      Description=AIDE auto-check timer

      [Timer]
      OnCalendar=*/2
      RandomizedDelaySec=1m
      AccuracySec=1us
      Persistent=true

      [Install]
      WantedBy=timers.target
    dest: /etc/systemd/system/aide-auto-check.timer
    mode: 0644
    owner: root
    group: root
    attributes: +i
  when: aide_auto_check is defined

- name: Commit AIDE install EL
  become: true
  shell:
    chdir: /etc
    cmd: git add aide.conf systemd/system/aide* logrotate.d/aide && git commit -a -m "Aide installed"
  args:
    executable: /bin/bash
  when: '"el" in release.stdout'

- name: Commit AIDE install Deb
  become: true
  shell:
    chdir: /etc
    cmd: git add aide systemd/system/aide* && git commit -a -m "Aide installed"
  args:
    executable: /bin/bash
  when: '"el" not in release.stdout'

- name: Service start
  become: true
  systemd:
    name: "{{ item }}"
    enabled: true
    state: restarted
    daemon_reload: true
  with_items:
    - aide-check.timer
    - aide-check.service

- name: Adminstop
  become: true
  command: /usr/local/sbin/adminstop-auto
  changed_when: false
...
