---
- name: Install util-linux
  yum:
    name: util-linux
    state: present
  when: '"el7" in release.stdout'

- name: Install tlog
  yum:
    name: tlog
    state: present
  when: 
    - '"el8" in release.stdout or "el9" in release.stdout'

- name: Install bsdutils
  package:
    name: bsdutils
    state: present
  when: '"generic" in release.stdout or "amd64" in release.stdout'
...
