---
- name: Check network service
  become: true
  shell: systemctl is-active network.service
  failed_when: false
  changed_when: false
  register: networkcheck
  when: '"el" in release.stdout'

- name: Check NetworkManager service
  become: true
  shell: systemctl is-active NetworkManager.service
  failed_when: false
  changed_when: false
  register: nmcheck
  when: '"el" in release.stdout'

- name: Check networking service
  become: true
  shell: systemctl is-active networking.service
  failed_when: false
  changed_when: false
  register: networkingcheck
  when: '"amd64" in release.stdout'

- name: Check systemd-networkd.service
  become: true
  shell: systemctl is-active systemd-networkd.service
  failed_when: false
  changed_when: false
  register: systemdnetworkd
  when: '"generic" in release.stdout'

- name: Set fact
  set_fact:
    netservice: network
  when: networkcheck.stdout == "active"

- name: Set fact
  set_fact:
    netservice: NetworkManager
  when: nmcheck.stdout == "active"

- name: Set fact
  set_fact:
    netservice: networking
  when: networkingcheck.stdout == "active"

- name: Set fact
  set_fact:
    netservice: systemd-networkd
  when: systemdnetworkd.stdout == "active"

- name: Install route-guard
  become: true
  template:
    src: ../files/route-guard.j2
    dest: /usr/local/sbin/route-guard
    owner: root
    group: root
    mode: '0750'
...
