---
- name: Check network service
  become: true
  command: systemctl is-active network.service
  failed_when: false
  changed_when: false
  register: networkcheck
  when: '"el" in release.stdout'

- name: Check NetworkManager service
  become: true
  command: systemctl is-active NetworkManager.service
  failed_when: false
  changed_when: false
  register: nmcheck
  when: '"el" in release.stdout'

- name: Check networking service
  become: true
  command: systemctl is-active networking.service
  failed_when: false
  changed_when: false
  register: networkingcheck
  when: '"Debian" in distro.stdout'

- name: Check systemd-networkd.service
  become: true
  command: systemctl is-active systemd-networkd.service
  failed_when: false
  changed_when: false
  register: sysdnetcheck
  when: '"Ubuntu" in distro.stdout'

- name: Set fact
  set_fact:
    netservice: network
  when:
    - '"el" in release.stdout'
    - networkcheck.stdout == "active"

- name: Set fact
  set_fact:
    netservice: NetworkManager
  when:
    - '"el" in release.stdout'
    - nmcheck.stdout == "active"

- name: Set fact
  set_fact:
    netservice: networking
  when:
    - '"Debian" in distro.stdout'
    - networkingcheck.stdout == "active"

- name: Set fact
  set_fact:
    netservice: systemd-networkd
  when:
    - '"Ubuntu" in distro.stdout'
    - sysdnetcheck.stdout == "active"

- name: Install route-guard
  become: true
  template:
    src: ../files/route-guard.j2
    dest: /usr/local/sbin/route-guard
    owner: root
    group: root
    mode: '0750'
...
