---
galaxy_info:
  role_name: terminal_logger
  author: Kresimir Lovric
  description: Installs script/tlog as part of SCDRM
  company: IBM

min_ansible_version: 2.9
github_branch: main
galaxy_tags:
  - scdrm
  - security
  - disaster_recovery
  - rhel
  - ids

dependencies: []
...
