# Check Git commits against recorded values
---
- name: Get commits for managed dirs EL
  become: true
  shell:
    chdir: "{{ item }}"
    cmd: set -o pipefail;git log | head -3 | awk '/commit/ {print $2}'
  args:
    executable: /bin/bash
  register: gitcommit
  with_items:
    - "{{ dirlist_el }}"
  when: '"el" in release.stdout'

- name: Get commits for managed dirs Deb
  become: true
  shell:
    chdir: "{{ item }}"
    cmd: set -o pipefail; git log | head -3 | awk '/commit/ {print $2}'
  args:
    executable: /bin/bash
  register: gitcommit
  changed_when: false
  with_items:
    - "{{ dirlist_deb }}"
  when: '"el" not in release.stdout'

- name: Compare commits
  become: false
  shell: 
    cmd: "set -o pipefail;echo {{ item.0 }} {{ item.1 }} | grep {{ item.2 }}"
  args:
    executable: /bin/bash
  with_together:
    - "{{ gitcommit | json_query('results[*].item') }}"
    - "{{ gitcommit | json_query('results[*].stdout') }}"
    - "{{ last_commit }}"
  delegate_to: localhost
  changed_when: false
...
