# Check Git commits against recorded values
---
- name: Get commits for managed dirs EL
  become: true
  shell:
    chdir: "{{ item }}"
    cmd: git log | head -3 | awk '/commit/ {print $2}'
  args:
    executable: /bin/bash
  register: elgitcommit
  with_items:
    - "{{ dirlist_el }}"
  when: '"el" in release.stdout'
  changed_when: false

- name: Get commits for managed dirs Deb
  become: true
  shell:
    chdir: "{{ item }}"
    cmd: git log | head -3 | awk '/commit/ {print $2}'
  args:
    executable: /bin/bash
  register: debgitcommit
  changed_when: false
  with_items:
    - "{{ dirlist_deb }}"
  when: '"el" not in release.stdout'

- name: Compare commits EL
  become: false
  shell:
    cmd: "echo {{ item.0 }} {{ item.1 }} | grep {{ item.2 }}"
  args:
    executable: /bin/bash
  with_together:
    - "{{ elgitcommit | json_query('results[*].item') }}"
    - "{{ elgitcommit | json_query('results[*].stdout') }}"
    - "{{ last_commit }}"
  delegate_to: localhost
  changed_when: false
  when: '"el" in release.stdout'

- name: Compare commits Deb
  become: false
  shell:
    cmd: "echo {{ item.0 }} {{ item.1 }} | grep {{ item.2 }}"
  args:
    executable: /bin/bash
  with_together:
    - "{{ debgitcommit | json_query('results[*].item') }}"
    - "{{ debgitcommit | json_query('results[*].stdout') }}"
    - "{{ last_commit }}"
  delegate_to: localhost
  changed_when: false
  when: '"el" not in release.stdout'
...
