# Record Git commits for managed dirs
---
- name: Get commits for managed dirs
  become: true
  shell: 
    chdir: "{{ item }}"
    cmd: git log | head -3 | awk '/commit/ {print $2}'
  register: gitcommit
  with_items: 
    - "{{ dirlist }}"

- name: Prepare host vars file
  become: true
  copy:
    content: | 
      last_commit:
    dest: "{{ scdrm_install_dir }}/host_vars/{{ inventory_hostname }}"
    force: yes
  delegate_to: localhost

- name: Record commits
  become: false
  blockinfile:
    path: "{{ scdrm_install_dir }}/host_vars/{{ inventory_hostname }}"
    block: |
      - {{ item.stdout }}
    #    path: {{ item.item }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.item }}"
    state: present
  with_items:
    - "{{ gitcommit.results }}"
  delegate_to: localhost

...
