# Record Git commits for managed dirs
---
- name: Get commits for managed dirs
  become: true
  shell:
    chdir: "{{ item }}"
    cmd: set -o pipefail && git log | head -3 | awk '/commit/ {print $2}'
  args:
    executable: /bin/bash
  register: gitcommit
  with_items:
    - "{{ dirlist_el }}"
  when: '"el" in release.stdout'

- name: Get commits for managed dirs
  become: true
  shell:
    chdir: "{{ item }}"
    cmd: set -o pipefail && git log | head -3 | awk '/commit/ {print $2}'
  args:
    executable: /bin/bash
  register: gitcommit
  with_items: 
    - "{{ dirlist_deb }}"
  when: '"el" not in release.stdout'

- name: Prepare host vars file
  become: true
  copy:
    content: | 
      last_commit:
    dest: "{{ scdrm_install_dir }}/host_vars/{{ inventory_hostname }}"
    force: true
    mode: 0640
    owner: root
  delegate_to: localhost

- name: Record commits
  become: true
  blockinfile:
    path: "{{ scdrm_install_dir }}/host_vars/{{ inventory_hostname }}"
    block: |
      - {{ item.stdout }}
    #    path: {{ item.item }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.item }}"
    state: present
  with_items:
    - "{{ gitcommit.results }}"
  delegate_to: localhost
...
