---
- name: Prepare for update
  become: true
  command: chattr -R -i /etc/scdrm/ 2>/dev/null
  failed_when: false
  changed_when: true

- name: Update config
  become: true
  lineinfile:
    path: /etc/scdrm/scdrm.conf
    regexp: '^DRYRUN='
    line: DRYRUN={{ dryrun }}
    state: present

- name: Lock config
  become: true
  command: chattr -R +i /etc/scdrm/ 2>/dev/null
  failed_when: false
  changed_when: true
...
