---
- name: Run adminstop-auto
  become: True
  shell: /usr/local/sbin/adminstop-auto
  register: adminstop
  failed_when: adminstop.rc != 0

- name: Update host_vars
  import_role: 
    name: change_tracking
  vars:
    update: yes
...
