---
galaxy_info:
  role_name: aide
  author: Kresimir Lovric
  description: Installs and configures AIDE as part of SCDRP
  company: IBM

min_ansible_version: 2.9
github_branch: main
galaxy_tags:
  - scdrm
  - security
  - disaster_recovery
  - rhel
  - ids

dependencies: []
...
