---
- name: Prepare directories for deletion 
  become: true
  failed_when: false
  changed_when: true
  shell: chattr -R -i "{{ item }}" 2>/dev/null
  args:
    executable: /bin/bash
  with_items:
    - /etc/scdrm
    - /etc/.git
    - /etc/.gitignore
    - /etc/systemd/system
    - /etc/systemd/system/timers.target.wants
    - /etc/logrotate.d
    - /usr/lib/systemd/.git
    - /usr/lib/systemd/.gitignore
    - /usr/lib64/security/.git
    - /usr/lib64/security/.gitignore
    - /lib/x86_64-linux-gnu/security/.git
    - /lib/x86_64-linux-gnu/security/.gitignore
    - /etc/aide.conf
    - /etc/aide/aide.conf.d/98_aide_scdrm
    - /usr/local/bin/adminstart
    - /usr/local/sbin/bash-guard
    - /usr/local/sbin/route-guard
    - /usr/local/sbin/aide-auto-check

- name: Prepare files for deletion
  become: true
  shell: chattr -i /usr/local/sbin/scdrm* /usr/local/sbin/adminst* 2>/dev/null
  args:
    executable: /bin/bash
  failed_when: false
  changed_when: true

- name: Remove .git EL
  become: true
  file:
    path: "{{ item }}/.git"
    state: absent
  with_items: "{{ dirlist_el }}"
  when: '"el" in release.stdout'

- name: Remove .gitignore EL
  become: true
  file:
    path: "{{ item }}/.gitignore"
    state: absent
  with_items: "{{ dirlist_el }}"
  when: '"el" in release.stdout'

- name: Remove .git Deb
  become: true
  ignore_errors: true
  file:
    path: "{{ item }}/.git"
    state: absent
  with_items: "{{ dirlist_deb }}"
  when: '"el" not in release.stdout'

- name: Remove .gitignore Deb
  become: true
  ignore_errors: true
  file:
    path: "{{ item }}/.gitignore"
    state: absent
  with_items: "{{ dirlist_deb }}"
  when: '"el" not in release.stdout'

- name: Uninstall SCDRM
  file:
    path: "{{ item }}"
    state: absent
  ignore_errors: true
  with_items:
    - /scdrm
    - /etc/scdrm
    - /etc/aide.conf
    - /etc/aide/aide.conf.d/98_aide_scdrm
    - /var/log/scdrm
    - /var/log/aide
    - /etc/logrotate.d/aide
    - /etc/logrotate.d/scdrm
    - /etc/systemd/system/scdrm.service
    - /etc/systemd/system/scdrm.service.wants
    - /etc/systemd/system/timers.target.wants/aide-auto-check.timer
    - /etc/systemd/system/timers.target.wants/aide-check.timer
    - /etc/systemd/system/timers.target.wants/scdrm-slow-check.timer
    - /etc/systemd/system/scdrm-slow-check.service
    - /etc/systemd/system/scdrm-slow-check.timer
    - /etc/systemd/system/aide-check.timer
    - /etc/systemd/system/aide-check.service
    - /etc/systemd/system/aide-auto-check.service
    - /etc/systemd/system/aide-auto-check.timer
    - /usr/local/bin/adminstart
    - /usr/local/sbin/scdrmd
    - /usr/local/sbin/adminstart1
    - /usr/local/sbin/adminstop
    - /usr/local/sbin/adminstart-auto
    - /usr/local/sbin/adminstop-auto
    - /usr/local/sbin/scdrm-install
    - /usr/local/sbin/scdrm-slow
    - /usr/local/sbin/scdrm-fast
    - /usr/local/sbin/scdrm-gitcron
    - /usr/local/sbin/scdrm-service-restart
    - /usr/local/sbin/route-guard
    - /usr/local/sbin/bash-guard
    - /usr/local/sbin/aide-auto-check

- name: Remove cron job GC
  cron:
    name: "SCDRM Git GC"
    minute: "16"
    hour: "16"
    day: "1"
    job: /usr/local/sbin/scdrm-gitcron
    user: root
    state: absent

- name: Remove packages
  package:
    name: "{{ item }}"
    state: absent
  with_items:
    - aide
    - tlog

- name: Reload systemd
  systemd:
    daemon_reload: true
...
