# Update SCDRM configuration
---
- name: Adminstart
  become: true
  import_role: 
    name: adminstart

- name: Prepare for update
  become: true
  failed_when: False
  shell: chattr -R -i /usr/local/sbin/scdrm* /usr/local/sbin/adminst* /usr/local/bin/adminstart /etc/systemd/system 2>/dev/null

- name: Check network service
  become: true
  shell: systemctl is-active network.service
  changed_when: false
  failed_when: false
  register: networkcheck

- name: Check NetworkManager service
  become: true
  shell: systemctl is-active NetworkManager.service
  failed_when: false
  changed_when: false
  register: nmcheck

- name: Set fact
  set_fact:
    netservice: network
  when: networkcheck.stdout == "active"

- name: Set fact
  set_fact:
    netservice: NetworkManager
  when: nmcheck.stdout == "active"

- name: Copy scdrmd
  become: true
  template:
    src: ../files/check.j2
    dest: /usr/local/sbin/scdrmd
    mode: 0750
    owner: root
    group: root
    attributes: +i

- name: Copy scdrm.conf
  become: true
  template:
    src: ../files/scdrm.j2
    dest: /etc/scdrm/scdrm.conf
    mode: 0755
    owner: root
    group: root
    attributes: +i

- name: Copy gitignore
  become: true
  copy:
    src: ../files/gitignore
    dest: /etc/.gitignore
    mode: 0640
    owner: root
    attributes: +i

- name: Copy cron-check
  become: true
  template:
    src: ../files/scdrm-slow.j2
    dest: /usr/local/sbin/scdrm-slow
    mode: '0750'
    owner: root
    group: root
    attributes: +i

- name: Copy fast-check
  become: true
  template:
    src: ../files/scdrm-fast.j2
    dest: /usr/local/sbin/scdrm-fast
    mode: '0750'
    owner: root
    group: root
    attributes: +i

- name: Copy scdrm-service-restart
  become: true
  template:
    src: ../files/scdrm-service-restart.j2
    dest: /usr/local/sbin/scdrm-service-restart
    mode: 0750
    owner: root
    group: root
    attributes: +i

- name: Setup Git GC cron
  cron:
    name: "SCDRM Git GC"
    minute: "16"
    hour: "16"
    day: "1"
    job: /usr/local/sbin/scdrm-gitcron
    user: root
    state: present

- name: Check SELinux
  become: false
  shell: /usr/sbin/getenforce
  register: selinux
  when:
    - disable_aide == "False"

- name: Copy aide.conf
  become: true
  template:
    src: ../../aide/files/aide
    dest: /etc/aide.conf
    mode: 0600
    owner: root
    group: root
    attributes: +i
  when: 
    - selinux.stdout != "Enforcing"
    - disable_aide == "False"

- name: Copy SELinux aide.conf
  become: true
  template:
    src: ../../aide/files/aide-selinux.conf
    dest: /etc/aide.conf
    mode: 0600
    owner: root
    group: root
    attributes: +i
  when: 
    - selinux.stdout == "Enforcing"
    - disable_aide == "False"

- name: Setup AIDE check timer
  become: true
  copy:
    content: |
      [Unit]
      Description=AIDE check timer

      [Timer]
      OnCalendar={{ aide_check }}
      RandomizedDelaySec=8h
      AccuracySec=1us

      [Install]
      WantedBy=timers.target
    dest: /etc/systemd/system/aide-check.timer
    mode: 0644
    owner: root
    group: root
    attributes: +i
  when: disable_aide == "False"

- name: Adminstop
  become: true
  import_role: 
    name: adminstop

- name: Restart SCDRMd
  become: true
  systemd:
    name: scdrm.service
    enabled: yes
    state: restarted
    daemon-reload: yes

- name: Restart AIDE
  become: true
  systemd:
    name: aide-check.timer
    enabled: yes
    state: restarted
    daemon-reload: yes
  when: disable_aide == "False"
...
