# This playbook removes 'adminssh' from your central management jumphost
---
- name: Remove adminssh
  hosts: localhost
  gather_facts: no
  vars_files: ./vars/main.yml
  tasks:
   - name: Remove files from localhost
     become: True
     file:
       path: "{{ item }}"
       state: absent
     with_items:
       - /usr/local/bin/adminssh
       - /usr/local/bin/scdrm-commit-hostvars
       - /scdrm
       - "{{ scdrm_install_dir }}/scdrm/host_vars"
       - "/home/{{ myuser }}/.scdrm_rc"

   - name: Remove scdrm-commit cron
     become: False
     cron:
       name: "SCDRM commit hostvars"
       minute: "1,31"
       job: /usr/local/bin/scdrm-commit-hostvars
       state: absent

   - name: Remove local bashrc functions
     become: False
     blockinfile:
       path: "/home/{{ myuser }}/.bashrc"
       block: |
         if [[ -s /home/{{ myuser }}/.scdrm_rc ]]
         then . /home/{{ myuser }}/.scdrm_rc
         fi
       marker: "##<!-- ANSIBLE MANAGED BLOCK -->"
       state: absent
...
