# This playbook removes 'adminssh' from your central management jumphost
---
- name: Remove adminssh
  hosts: localhost
  gather_facts: no
  vars_files: ./vars/main.yml
  tasks:
   - name: Remove files from localhost
     become: yes
     file:
       path: "{{ item }}"
       state: absent
     with_items:
       - /usr/local/bin/adminssh
       - /usr/local/bin/scdrm-commit
       - /scdrm

   - name: Remove scdrm-commit cron
     become: no
     cron:
       name: "SCDRM commit hostvars"
       minute: "1,31"
       job: /usr/local/bin/scdrm-commit
       state: absent
...
