---
- name: Acknowledge change while in paranoid mode
  hosts: all
  gather_facts: false
  serial: 96
  ignore_errors: true
  vars_files: ./vars/main.yml
  tasks:
    - name: Kill scdrm-paranoid
      become: True
      shell: pkill scdrm-paranoid
      args:
        executable: /bin/bash
      changed_when: false
      ignore_errors: true
...
