---
- name: Report on changed/deleted files
  hosts: all
  serial: 96
  ignore_errors: yes
  vars_files: ./vars/main.yml
  tasks:
    - name: Clean tmp
      become: false
      delegate_to: localhost
      run_once: true
      shell:
        chdir: "{{ scdrm_install_dir }}/tmp"
        cmd: "rm -f *"
      args:
        executable: /bin/bash
      changed_when: true

    - name: Collect SCDRM report
      fetch:
        flat: true
        src: /var/log/scdrm/report
        dest: "{{ scdrm_install_dir }}/tmp/{{ inventory_hostname }}"
      changed_when: false

    - name: Log report
      become: false
      shell:
        cmd: "egrep -r 'DELETED|CHANGED|AIDE ALERT' {{ scdrm_install_dir }}/tmp | rev | cut -d'/' -f1 | rev > {{ scdrm_install_dir }}/reports/scdrm-report-$(date +%F).txt"
      args:
        executable: /bin/bash
      delegate_to: localhost
      run_once: true
      changed_when: true
...
