# Cleanup after test playbook
# 
---
- name: Installs httpd and tests SCDRM restore function
  hosts: all
  gather_facts: no
  serial: 96
  ignore_errors: yes
  vars_files: ./vars/main.yml
  roles:
    - role: get_kernel
    - role: adminstart
  tasks:
    - name: Stop httpd
      become: True
      systemd:
        name: httpd
        enabled: no
        state: stopped
      when: '"el" in release.stdout'

    - name: Stop Apache2
      become: True
      systemd:
        name: apache2
        enabled: no
        state: stopped
      when: '"el" not in release.stdout'

    - name: Remove httpd
      become: True
      yum:
        name: httpd
        state: absent
      when: '"el" in release.stdout'

    - name: Remove apache2
      become: True
      package:
        name: apache2
        state: absent
      when: '"el" not in release.stdout'

    - name: Adminstop
      import_role:
        name: adminstop
...
